apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-web-deployment
  labels:
    app: app-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-web
  template:
    metadata:
      labels:
        app: app-web
    spec:
      containers:
      - name: app-web-cnt
        image: registry.localhost:5000/app-web-img:staging
        envFrom:
          - secretRef:
              name: mysecret
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-web-svc
  labels:
    app: app-web
spec:
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31080  # external access
    name: client
  selector:
    app: app-web
  type: NodePort

