apiVersion: v1
kind: PersistentVolume
metadata:
  name: ts-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/ts_k3dvol"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ts-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi

